_wandb:
    value:
        cli_version: 0.25.0
        e:
            7qksnzluhivknhr9h8zf4y17q86xjefr:
                codePath: experiments/cnn_benchmarks/bench_ptorch.py
                codePathLocal: experiments/cnn_benchmarks/bench_ptorch.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "254520852480"
                        used: "243345117184"
                email: jeff.jambe@student.kuleuven.be
                executable: /home/cyuzuzo/.pyenv/versions/3.10.19/bin/python
                git:
                    commit: 2c73a51c28715412354a0502658844f5f98a1ff6
                    remote: git@github.com:cyuzuzo-j/learning_with_projections.git
                host: cyuzuzo
                memory:
                    total: "16595554304"
                os: Linux-6.18.7-arch1-1-surface-x86_64-with-glibc2.42
                program: /home/cyuzuzo/thesisV5/experiments/cnn_benchmarks/bench_ptorch.py
                python: CPython 3.10.19
                root: /home/cyuzuzo/thesisV5
                startedAt: "2026-03-04T21:23:30.543087Z"
                writerId: 7qksnzluhivknhr9h8zf4y17q86xjefr
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 12
                - 41
            "2":
                - 1
                - 12
                - 41
            "3":
                - 13
                - 61
            "4": 3.10.19
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
batch_size:
    value: 8
bilinear_matrix_method:
    value: parr
bilinear_method:
    value: fast
bilinear_projection_num_newton_steps:
    value: 10
cross_entropy_lambda:
    value: 5
cross_entropy_method:
    value: fixed_point
cross_entropy_num_steps:
    value: 10
eval_every:
    value: 50
framework:
    value: ptorch_parr
matmul_proj_method:
    value: seq
max_steps:
    value: 10000
opt_lr:
    value: 10000
optimizer:
    value: ProjectionAdadelta
patience:
    value: 10
run_number:
    value: 1
seed:
    value: 43
task:
    value: MNIST
