wandb_version: 1

alpha:
  value: 1.2020730574806588
architecture:
  value: '[4, 8, 16]'
batch_size:
  value: 32
eval_every:
  value: 100
g:
  value: 0.021856687300171138
lr:
  value: 0.0021095145001740973
max_steps:
  value: 5000
optimizer:
  value: AlternatingProjections
patience:
  value: 15
seed:
  value: 43
