_wandb:
    value:
        cli_version: 0.25.0
        e:
            r30cay5sf5kl203zzr4r0yacsdcd34i9:
                codePath: experiments/cnn_benchmarks/bench_pjax_combined.py
                codePathLocal: experiments/cnn_benchmarks/bench_pjax_combined.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "254520852480"
                        used: "243161276416"
                email: jeff.jambe@student.kuleuven.be
                executable: /home/cyuzuzo/.pyenv/versions/3.10.19/bin/python
                git:
                    commit: 9ce0cbdb1236da07075a2bbe4cf54e092184bee0
                    remote: git@github.com:cyuzuzo-j/learning_with_projections.git
                host: cyuzuzo
                memory:
                    total: "16595554304"
                os: Linux-6.18.7-arch1-1-surface-x86_64-with-glibc2.42
                program: /home/cyuzuzo/thesisV5/experiments/cnn_benchmarks/bench_pjax_combined.py
                python: CPython 3.10.19
                root: /home/cyuzuzo/thesisV5
                startedAt: "2026-03-04T16:36:02.094237Z"
                writerId: r30cay5sf5kl203zzr4r0yacsdcd34i9
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 12
                - 41
            "2":
                - 1
                - 12
                - 41
            "3":
                - 13
                - 61
            "4": 3.10.19
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
batch_size:
    value: 8
eval_every:
    value: 50
framework:
    value: pjax
max_steps:
    value: 10000
opt_steps_per_update:
    value: 50
optimizer:
    value: DouglasRachford
patience:
    value: 10
run_number:
    value: 1
seed:
    value: 43
task:
    value: MNIST
